### ISSUE TITLE
Allocate new groupId and package for Apollo 2.x

### ISSUE THREAD

**Issue by udoprog** [spotify/apollo#115]
This is suggestion for the next Major version of Apollo.

Because Apollo is a multi-module project that also exposes an API, there are many opportunities for accidental binary compatibility with `1.x` at runtime. This threatens the stability of projects using Apollo, especially in complex environments.

My suggestion is to introduce a new `groupId` (`com.spotify.apollo2`) and move everything into new packages (`com.spotify.apollo2`). This way, maven dependencies are explicit, and major version compatibility would have to be explicitly addressed instead of by accident.

**Comment by mattnworb** [comment]
+1

**Comment by pettermahlen** [comment]
The suggested change would add to the upgrade cost for users, because they would have to change their application code to use the new packages.

I think the package and artifact name change is mostly useful if different versions of Apollo are included via different paths in the set of transitively included dependencies for a particular service. And given the way that Apollo services are generally packaged, I don't see that happening easily. I think the suggested pattern is more clearly useful for more low-level libraries than Apollo. 

I'm not convinced that this is a net positive for users. Are there maybe cases where, for instance, third-party libraries that use maybe `Request` or `Response` would create conflicts? It seems like that would more likely lead to duplication in the case that there are no differences in those interfaces - library developers would have to maintain different versions of the library, or translation code from one version to another, even if there is no actual difference in the interfaces.

**Comment by udoprog** [comment]
A fundamental reason why this is important is because it can easily be broken due to transitive dependencies.

`module1` depends on `1.x`, and `module2` depends on `2.x`. Both of them can be happily installed in either `1.x` or `2.x` but `module2` uses an interface in a way that was accessible at compile time, but no longer is at runtime. With my suggestion, it would not be possible to install module2, since it no longer implements `com.spotify.apollo.module.ApolloModule`, even if it's accidentally included through a bad Maven dependency.

Library developers explicitly having to maintain different versions is also the point. That is effectively the case without this scheme regardless. The difference is that valuing convenience over correctness is like relying on duck-typing and due diligence. The end user has to keep a close eye on their dependency graph. If backwards compatibility is desired, and possible a `2.x` -> `1.x` shim implementing `1.x` API's can be provided. But it should be done explicitly.

**Comment by pettermahlen** [comment]
I understand the reasoning, but I don't see Apollo being a transitive dependency very often. In particular not apollo-api (`Request`, `Response`, and the like), but I do see that changing their package names would add to the upgrade costs for users.

I think the module use case you mention is interesting, because it highlights a case where it is possible to have a transitive Apollo dependency. Perhaps a good tradeoff is changing package names in apollo-core, thereby forcing modules that add a transitive dependency to Apollo to use the right version.

**Comment by pettermahlen** [comment]
Hm, I guess it is perfectly possible for somebody to write a non-module library depending on the apollo-api types, and for that to be included in the transitive set of dependencies, so that argument isn't a very good one.

I'm still in doubt whether the guaranteed upgrade cost increase is likely to be offset by the potential time and pain saved from avoiding dependency conflicts. The latter increases with 'depth' in dependency graphs and apollo is likely to usually be quite close to the top level of dependency graphs.

**Comment by pettermahlen** [comment]
I'm guessing the source of inspiration for this request is something along the lines of http://jakewharton.com/java-interoperability-policy-for-major-version-updates/. If so, then perhaps what we need to decide on is whether Apollo is a 'significantly foundational library' or not. Or parts of it might be foundational.

**Comment by Yarin78** [comment]
This would indeed be a painful change to have to make. Would be nice to get some feedback from our users what they think. Or if we could find out how likely this is to become a problem.

Btw, this is essentially how .NET dependencies work - the version is part of the type.

**Comment by spkrka** [comment]
I vote for doing it Right(tm), by renaming packages and artifactid - I don't think it would be very painful to upgrade, you can probably even do it with a global search&replace on imports

**Comment by udoprog** [comment]
It's also something that should only be necessary for Major upgrades. They should be rare and inherently come with other breaking changes.

I'm not sure I agree about isolated parts capability of being 'foundational libraries' and do proper versioning solely for them. If something has the same qualified name as something else it will override the implementation at runtime, even if outside of the 'blessed API'.

**Comment by pettermahlen** [comment]
I'm leaning more and more towards 'better safe than sorry', and towards feeling that the predictable, slight pain of a search-and-replace (and pain for framework developers of applying patches to two incompatible branches) is better than the unpredictable and severe pain of runtime conflicts. Even though the latter is likely to be rare in the case of Apollo.

I disagree with calling it 'proper versioning', though. :) This approach is most definitely a workaround for how dependencies are managed in the Java ecosystem. But even if it's a hack, it's probably the best approach there is.

**Comment by lepistone** [comment]
Closing, since there are no immediate plans for a major release.
