### ISSUE TITLE
More graceful shutdown

### ISSUE THREAD

**Issue by pettermahlen** [spotify/apollo#120]
Currently, when shutting down, there's a fairly high chance that requests in process will fail. This has been somewhat intentional, since clients in a distributed system should be resilient to transient failures anyway. It turns out that a large number of service clients in our internal ecosystem at least are not sufficiently resilient, and that improving the shutdown process to increase the chance of requests getting successfully processed before the service stops will improve the user experience.

Known issues to address:
- Clients can be closed while they still have outstanding requests, leading to failures when replies come in.
- Servers (like `HttpServerImpl`) don't wait for all outstanding requests to finish processing before stopping.

**Comment by udoprog** [comment]
I've built a kind of abstraction to deal with this in Heroic:
https://github.com/udoprog/tiny-async-java#managed-references

Keep in mind that I've built a separate future abstraction, but the [ConcurrentManaged](https://github.com/udoprog/tiny-async-java/blob/master/tiny-async-core/src/main/java/eu/toolchain/async/concurrent/ConcurrentManaged.java) implementation could be ported to CompletableFuture (and it's something I've intended to do when I get some time).

The overall function is described [in the README](https://github.com/udoprog/tiny-async-java#managed-references), the [Managed interface is fairly documented](https://github.com/udoprog/tiny-async-java/blob/master/tiny-async-api/src/main/java/eu/toolchain/async/Managed.java) and there are examples here.

The only requirement is that startup and shutdown procedures are asynchronous (e.g `start(...)` and `stop(...)` returns a listenable future). All access to the managed reference has to be governed by borrowing it. The most convenient way to do it is to use `Managed#doto`, like this:

```java
final Managed<Handler> m = ...;

return m.doto(handler -> {
    return doSomethingAsync(handler);
});
```

Then the managed reference is released with the future.

On another note, I've built the following filter to return 403 while Heroic is shutting down:
https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/servlet/ShutdownFilter.java

**Comment by jo-ri** [comment]
There seems to be at least two different issues related to shutting down an Apollo service:
1) A number of incoming requests will fail causing the ‘failed request rate’ to increase and potentially cause problems for clients of the service that is shutting down, if those clients  do not handle errors properly.

2) Problems internal to the service itself, primarily errors in logs, but may also impact services that perform sequences of actions that should be atomic without transaction support.

Since Hermes requests are sent over a continuously open socket, there seems to be no way to handle (1) by gracefully shutting down Apollo (an HTTP/1 server can stop accepting new connections). While waiting for outstanding requests to finish, new requests will arrive causing the same number of failed requests given a constant request rate. To address both (1) and (2), it seems one must stop requests from being sent to the service before shutting it down. A way to do that is using the overlapping+gracePeriod features of Helios. How to accomplish this is extensively described here: https://ghe.spotify.net/helios/helios/blob/master/docs/zero_downtime_deploys.md

It would be possible to add a graceful shutdown of Apollo and make the Hermes server reply with an error code to all incoming requests during the shutdown period, but that would only address problem (2), and that may not be worth the effort given that the helios solution exists which solves both problems.

**Comment by ulzha** [comment]
Is there really no suitable fronting component that can support consistent redirection of new requests to the newly deployed service instance? The ["we cannot guarantee zero downtime"](https://ghe.spotify.net/helios/helios/blob/master/docs/zero_downtime_deploys.md) excuse seems to be made on the grounds of impossibility to invalidate client DNS caches, but should we give up there?

We should be able to failover internally for example by redirecting the old port(s) to the new one (and keep the cheap redirect in place for days or weeks) and send a simple immediate kill to the old instance...

**Comment by mattnworb** [comment]
@ulzha seems like that would be something that could be provided at a level above the Apollo process, and not within this codebase itself, isn't it? Also note that the document you link to is from an internal repository.

**Comment by TheIndifferent** [comment]
@jo-ri I would add 3, which in my opinion is fixable and quite important one for microservice deploys:
1. service A receives a request from a Client (C)
2. A sends request to service K to act on client request.
3. on successfully completed future, A sends request to service L to act on client request.
4. on successfully completed future, A sends request to service M to act on client request.
5. on successfully completed future, A composes response and responds to C.

Current shutdown procedure can break somewhere between 2 and 5, meaning that we end up with inconsistent data in case of creation/mutation requests, which will be pretty much undetectable and may lead to long-term bad user experience.
So I would suggest that shutdown procedure should stop accepting incoming requests while waiting for current requests chains to finish. That will cause failure for C, but will not cause data inconsistencies with long-term bad user experience.

**Comment by jo-ri** [comment]
@TheIndifferent Yea, right, I intended that kind of scenario to be included as one kind of sequence needing transaction support mentioned in issue 2, but it could very well be it's own issue, although I think the rest applies to 2 and 3 equally in that case. Thanks for the comprehensive description, sorry for being vague.

**Comment by lepistone** [comment]
Improvements on shutdown are happening in other places (see gRPC and in general infrastructure). Closing.
