### ISSUE TITLE
apollo-bom doesn't use scopes in dependencyManagement

### ISSUE THREAD

**Issue by mattnworb** [spotify/apollo#121]
I noticed in a project I am working on that a dependency on `apollo-test:1.1.0:test` ends up dragging in `com.google.auto.value:auto-value:1.1`. I expected the latter to have `<scope>provided</scope>` in apollo-test, since AFAIK code generated by auto-value has no dependencies on auto-value (and scope=provided is what [the auto-value docs recommend](https://github.com/google/auto/blob/master/value/userguide/index.md).

But I noticed that in the apollo-bom, [none of the modules under the comment for "provided scope" actually have scope=provided](https://github.com/spotify/apollo/blob/v1.1.0/apollo-bom/pom.xml#L223-L238). Is that an oversight? Or a limitation of the bom concept?

**Comment by pettermahlen** [comment]
I'm not sure - maybe @rouzwawi has some more insights. I've been trying to figure out about `<dependencyManagement/>` and `<scope/>`, and they seem to interact in confusing ways. http://stackoverflow.com/questions/7588492/maven-dependency-resolution-and-scope-overriding/7597596 illustrates that fairly well - essentially, dependency management takes precedence over transitively inherited definitions. Not sure if that's an issue for real, since it seems like you can always override the scope in your local pom if needed.

From what I can understand, it would be better to define the intended scopes in the `<dependencyManagement/>` section in the BOM.

**Comment by rouzwawi** [comment]
The idea we had with the BOM was to have a `<dependencyManagement>` section that globally selected the versions of libraries used. I left all of the scope settings to be local to the depending module to specify.

So it's not an oversight that the BOM does not specify any scopes, it just expects all modules to directly specify how they like to depend on a library.

**Comment by rouzwawi** [comment]
[apollo-test does not specify a provided scope for auto-value](https://github.com/spotify/apollo/blob/2fd92750a0d2c1f77ab1e2cd275b2b5c46dd8b41/apollo-test/pom.xml#L44-L47) though. That might be the cause of what you see.

**Comment by mattnworb** [comment]
@rouzwawi that makes sense -  I think that is exactly the issue.
