### ISSUE TITLE
How to get the Request protocol from Request.uri()?

### ISSUE THREAD

**Issue by zzzz** [spotify/apollo#129]
When I made a request and try to capture the Request protocol, I can't get it from Request.url().  How to do get it?

According to the W3 doc, it should have it from the Reqest-URI
https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

Example:
GET http://www.w3.org/pub/WWW/TheProject.html HTTP/1.1

How do I get the "HTTP/1.1"?

**Comment by pettermahlen** [comment]
I guess to be precise, the `HTTP/1.1` is a part of the request line, but not the request URI. Apollo doesn't retain that information; a part of the reason is that it's not normally a good idea for code to 'reach out' of it's abstraction layer to understand how it was called. But mostly, it's not something that we've seen a need for. What is the problem you're trying to solve? I wonder if there's a need to get some kind of request metadata beyond what's in the URI, or if it's something that could and should be solved some other way.

**Comment by zzzz** [comment]
We need to use for logging analytic purpose.  Is it possible to get that piece of data from another method after getting from abstraction layer?  I saw the native JAVA request from servlet can get those information.  http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRequestURI().  Any possible to get apollo support it?

**Comment by pettermahlen** [comment]
Anything is possible with software. :) I'm not completely sure of the return on investment of making a change to support only this use case, though, so for the moment, I'm not going to prioritise it. If you feel like working on a PR, I would suggest investigating some kind of generic request metadata that servers (like the jetty-http-server) can populate with things that are relevant for them.
