### ISSUE TITLE
Add Middleware to a set o routes

### ISSUE THREAD

**Issue by jonhkr** [spotify/apollo#166]
Hi,
Is it possible to add a `Middleware` to a set of routes without registering the middleware in every route?

**Comment by pettermahlen** [comment]
You can use `Stream` operators, like so:

```
Stream<Route<?>> routes = Stream.of(route1, route2, route3)
     .map(route -> route.withMiddleware(myMiddleware));
```

That's a large reason we decided to go with `Stream`s of `Route`s in the `RoutingEngine` methods; so as to avoid having to go back and forth between collections and streams when initialising applications. I have a slightly bad feeling about using streams this way (mostly because of terminal operations), but so far I'm not aware of any actual problems.

Please close if this answers your question!

**Comment by jonhkr** [comment]
Thanks @pettermahlen I'll try that.
